config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  before_save { self.email = email.downcase }
  validates :username, presence: true, uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = 'Article was successfully created'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = 'Article was successfully updated!'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show; end

  def destroy
    @article.destroy
    flash[:notice] = 'Article was deleted successfully!'
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Your account was updated successfully!'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user.destroy
    flash[:notice] = 'User was deleted successfully!'
    redirect_to articles_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'img-circle')
  end
end

app/views/articles/_article.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Created by</th>
    <th>Created at</th>
    <th>Last updated</th>
  </tr>

  <% obj.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <td><%= article.user.username if article.user %></td>
      <td><%= time_ago_in_words(article.created_at) %> ago</td>
      <td><%= time_ago_in_words(article.updated_at) %> ago</td>
      <td><%= link_to "Edit", edit_article_path(article) %></td>
      <td><%= link_to "Show", article_path(article) %></td>
      <td><%= link_to "Delete", article_path(article), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Back to all articles", articles_path %>

app/views/articles/edit.html.erb
<h2>Edit existing article</h2>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>All the articles</h1>
<%= will_paginate %>
<p>
  <%= link_to "Create a new article", new_article_path %>
</p>
<%= render 'article', obj: @articles %>
<br>
<%= link_to "Home Page", root_path%>
<%= will_paginate %>

app/views/articles/new.html.erb
<h1>Create an Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2>Showing selected article</h2>
<% if @article.user %>
    <div>
      <ul>
        <li>Created by:</li>
        <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
        <li><%= link_to @article.user.username, user_path(@article.user) %></li>
        <li><%= link_to @article.user.email, user_path(@article.user) %></li>
        <li><small><%= pluralize(@article.user.articles.count, 'article') if @article.user.articles %></small></li>
      </ul>
    </div>
<% end %>
<p>Title: <%= @article.title %></p>
<p>Description: <%= @article.description %></p>

<%= link_to "Edit this article", edit_article_path(@article) %> |
<%= link_to "Back to all articles", articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <ul>
        <li><%= msg %></li>
    </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Page Title</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
      * {
          box-sizing: border-box;
      }

      /* Style the body */
      body {
          font-family: Arial, Helvetica, sans-serif;
          margin: 0;
      }

      /* Header/logo Title */
      .header {
          padding: 10px;
          text-align: center;
          background: #1abc9c;
          color: white;
      }

      /* Increase the font size of the heading */
      .header h1 {
          font-size: 40px;
      }

      /* Sticky navbar - toggles between relative and fixed, depending on the scroll position. It is positioned relative until a given offset position is met in the viewport - then it "sticks" in place (like position:fixed). The sticky value is not supported in IE or Edge 15 and earlier versions. However, for these versions the navbar will inherit default position */
      .navbar {
          overflow: hidden;
          background-color: #333;
          position: sticky;
          position: -webkit-sticky;
          top: 0;
      }

      /* Style the navigation bar links */
      .navbar a {
          float: left;
          display: block;
          color: white;
          text-align: center;
          padding: 14px 20px;
          text-decoration: none;
      }


      /* Right-aligned link */
      .navbar a.right {
          float: right;
      }

      /* Change color on hover */
      .navbar a:hover {
          background-color: #ddd;
          color: black;
      }

      /* Active/current link */
      .navbar a.active {
          background-color: #666;
          color: white;
      }

      /* Column container */
      .row {
          display: -ms-flexbox; /* IE10 */
          display: flex;
          -ms-flex-wrap: wrap; /* IE10 */
          flex-wrap: wrap;
      }

      /* Create two unequal columns that sits next to each other */
      /* Sidebar/left column */
      .side {
          -ms-flex: 30%; /* IE10 */
          flex: 30%;
          background-color: #f1f1f1;
          padding: 20px;
      }

      /* Main column */
      .main {
          -ms-flex: 70%; /* IE10 */
          flex: 70%;
          background-color: white;
          padding: 20px;
      }

      /* Fake image, just for this example */
      .fakeimg {
          background-color: #aaa;
          width: 100%;
          padding: 20px;
      }

      /* Footer */
      .footer {
          padding: 20px;
          text-align: center;
          background: #ddd;
      }

      /* Responsive layout - when the screen is less than 700px wide, make the two columns stack on top of each other instead of next to each other */
      @media screen and (max-width: 700px) {
          .row {
              flex-direction: column;
          }
      }

      /* Responsive layout - when the screen is less than 400px wide, make the navigation links stack on top of each other instead of next to each other */
      @media screen and (max-width: 400px) {
          .navbar a {
              float: none;
              width: 100%;
          }
      }
  </style>
</head>
<body>

<div class="header">
  <h1>My Website</h1>
</div>

<div class="navbar">
  <a href=<%= root_path%> class="active">Home</a>
  <a href=<%= about_path%>>About</a>
  <a href="#">Link</a>
  <a href="#" class="right">Login</a>
</div>

<div class="row">
  <div class="side">
    <h2>Me</h2>
    <h5>Photo of me:</h5>
    <div class="fakeimg" style="height:200px;">Image</div>
    <p>Some text about me in culpa qui officia deserunt mollit anim..</p>
    <h3>More Text</h3>
    <p>Lorem ipsum dolor sit ame.</p>
    <div class="fakeimg" style="height:60px;">Image</div><br>
    <div class="fakeimg" style="height:60px;">Image</div><br>
    <div class="fakeimg" style="height:60px;">Image</div>
  </div>
  <div class="main">
    <h2>About HEADING</h2>
    <h5>Title description, Dec 7, 2017</h5>
    <div class="fakeimg" style="height:200px;">Image</div>
    <p>Some text..</p>
    <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
    <br>
    <h2>TITLE HEADING</h2>
    <h5>Title description, Sep 2, 2017</h5>
    <div class="fakeimg" style="height:200px;">Image</div>
    <p>Some text..</p>
    <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
  </div>
</div>

<div class="footer">
  <h2>Footer</h2>
</div>

</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Page Title</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
      * {
          box-sizing: border-box;
      }

      /* Style the body */
      body {
          font-family: Arial, Helvetica, sans-serif;
          margin: 0;
      }

      /* Header/logo Title */
      .header {
          padding: 10px;
          text-align: center;
          background: #1abc9c;
          color: white;
      }

      /* Increase the font size of the heading */
      .header h1 {
          font-size: 40px;
      }

      /* Sticky navbar - toggles between relative and fixed, depending on the scroll position. It is positioned relative until a given offset position is met in the viewport - then it "sticks" in place (like position:fixed). The sticky value is not supported in IE or Edge 15 and earlier versions. However, for these versions the navbar will inherit default position */
      .navbar {
          overflow: hidden;
          background-color: #333;
          position: sticky;
          position: -webkit-sticky;
          top: 0;
      }

      /* Style the navigation bar links */
      .navbar a {
          float: left;
          display: block;
          color: white;
          text-align: center;
          padding: 14px 20px;
          text-decoration: none;
      }


      /* Right-aligned link */
      .navbar a.right {
          float: right;
      }

      /* Change color on hover */
      .navbar a:hover {
          background-color: #ddd;
          color: black;
      }

      /* Active/current link */
      .navbar a.active {
          background-color: #666;
          color: white;
      }

      /* Column container */
      .row {
          display: -ms-flexbox; /* IE10 */
          display: flex;
          -ms-flex-wrap: wrap; /* IE10 */
          flex-wrap: wrap;
      }

      /* Create two unequal columns that sits next to each other */
      /* Sidebar/left column */
      .side {
          -ms-flex: 30%; /* IE10 */
          flex: 30%;
          background-color: #f1f1f1;
          padding: 20px;
      }

      /* Main column */
      .main {
          -ms-flex: 70%; /* IE10 */
          flex: 70%;
          background-color: white;
          padding: 20px;
      }

      /* Fake image, just for this example */
      .fakeimg {
          background-color: #aaa;
          width: 100%;
          padding: 20px;
      }

      /* Footer */
      .footer {
          padding: 20px;
          text-align: center;
          background: #ddd;
      }

      /* Responsive layout - when the screen is less than 700px wide, make the two columns stack on top of each other instead of next to each other */
      @media screen and (max-width: 700px) {
          .row {
              flex-direction: column;
          }
      }

      /* Responsive layout - when the screen is less than 400px wide, make the navigation links stack on top of each other instead of next to each other */
      @media screen and (max-width: 400px) {
          .navbar a {
              float: none;
              width: 100%;
          }
      }
  </style>
</head>
<body>

<div class="header">
  <h1>My Website</h1>
</div>

<div class="navbar">
  <a href=<%= root_path%>>Home</a>
  <a href=<%= about_path%>>About</a>
  <a href=<%= articles_path%>>Alpha Blog</a>
  <a href=<%= users_path%>>Alpha Blog Users</a>
  <a href="#" class="right">Login</a>
</div>

<div class="row">
  <div class="side">
    <h2>Me</h2>
    <h5>Photo of me:</h5>
    <div class="fakeimg" style="height:200px;">Image</div>
    <p>Some text about me in culpa qui officia deserunt mollit anim..</p>
    <h3>More Text</h3>
    <p>Lorem ipsum dolor sit ame.</p>
    <div class="fakeimg" style="height:60px;">Image</div><br>
    <div class="fakeimg" style="height:60px;">Image</div><br>
    <div class="fakeimg" style="height:60px;">Image</div>
  </div>
  <div class="main">
    <h2>Home HEADING</h2>
    <h5>Title description, Dec 7, 2017</h5>
    <div class="fakeimg" style="height:200px;">Image</div>
    <p>Some text..</p>
    <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
    <br>
    <h2>TITLE HEADING</h2>
    <h5>Title description, Sep 2, 2017</h5>
    <div class="fakeimg" style="height:200px;">Image</div>
    <p>Some text..</p>
    <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
  </div>
</div>

<div class="footer">
  <h2>Footer</h2>
</div>

</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <h2><%= pluralize(obj.errors.count, "error") %>  prohibited from being saved!</h2>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_for @user do |f| %>
  <p>
    <%= f.label :username %><br/>
    <%= f.text_field :username, placeholder: 'Enter Username' %>
  </p>
  <p>
    <%= f.label :email %><br/>
    <%= f.email_field :email, placeholder: 'Enter Email' %>
  </p>
  <p>
    <%= f.label :password %><br/>
    <%= f.password_field :password, placeholder: 'Enter Password' %>
  </p>
  <p>
    <%= f.submit(@user.new_record? ? 'Sign Up' : 'Update Account') %>
  </p>
<% end %>

<%= link_to "Back to all articles", articles_path %>

app/views/users/edit.html.erb
<h1>Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>All the users</h1>
<p>
  <%= link_to "Create a new user", signup_path %>
</p>
<%= will_paginate %>
<table>
  <tr>
    <th>ID</th>
    <th>User Image</th>
    <th>Username</th>
    <th>Email</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= link_to gravatar_for(user), user_path(user) %></td>
      <td><%= link_to user.username, user_path(user) %></td>
      <td><%= link_to user.email, user_path(user) %></td>
      <td><small><%= pluralize(user.articles.count, 'article') if user.articles %></small></td>
      <td><%= link_to "Update", edit_user_path(user) %></td>
      <td><%= link_to "Show", user_path(user) %></td>
      <td><%= link_to "Delete", user_path(user), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to "Home Page", root_path%>
<%= will_paginate %>

app/views/users/new.html.erb
<h1>Signup for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Welcome to <%= @user.username %>'s page</h1>
<%= gravatar_for @user, size: 150 %>
<h2><%= @user.username %>'s articles</h2>
<%= will_paginate @user_articles %>
<%= render 'articles/article', obj: @user_articles %>
<%= will_paginate @user_articles %>